#ifndef COMMON_H
#define COMMON_H


#define MAX_VOLUME 128

#define SFX_CHANNEL_MENU 3

enum car_sprite_idx {
 	CAR_SPRITE_REAR,
 	CAR_SPRITE_RIGHT1,
 	CAR_SPRITE_RIGHT2,
 	CAR_SPRITE_LAST
};

enum car_model_type {
 	CAR_MODEL_IMPREZIA = 0,
 	CAR_MODEL_LOTUS,
 	CAR_MODEL_FALCON,
 	CAR_MODEL_TT,
 	CAR_MODEL_TRUENO,
 	CAR_MODEL_VIPER,
 	CAR_MODEL_NSX,
 	CAR_MODEL_HART,
 	CAR_MODEL_DELTA,
 	CAR_MODEL_LANCER,
 	CAR_MODEL_LAST
};

#endif